/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.33
 * Generated at: 2016-04-22 04:18:08 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.ArrayList;

public final class star_002dpage_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/WEB-INF/var.jsp", Long.valueOf(1461290203000L));
    _jspx_dependants.put("/WEB-INF/header.jsp", Long.valueOf(1461298662000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("java.util.ArrayList");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=ISO-8859-1\">\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"css/styles.css\">\n");
      out.write("<title>FabFlix</title>\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("<!-- This File holds the Login Details and other Globals -->\n");

	// This is the Login for the DB
	String DB_USER= "root"; 
	String DB_PASS="pops711";
	// This is the location of the Login Portal
	String loginPath="/Index";
	// This is the location of the Login-Authentication
	String authLoginPath="Login";	
	// This is the location of the Logout script
	String logoutPath="Logout";	
	//This is the location of the HomePage
	String homePath="Main";
	// This is the location of the Search Page
	String searchPath="";	
	// This is the location of the General Browsing Page and the sub-pages
	String browsePath="browse.jsp";
	String browseGenre="Browse?by=genre";
	String browseTitle="Browse?by=title";
	// This is the location of the movie-list after you find one.
	String movieListPath="MovieList";
	// This is the Cart location.
	String cartPath="Cart";
	// This is the CheckOut location.
	String checkoutPath="Checkout";
	// This confirms the CC is legit
	String ccAuthPath="CheckCC";

      out.write("\n");
      out.write("<header class=\"siteHeader\">\n");
      out.write("\t<nav class=\"navbar\">\n");
      out.write("\t\t<ul class=\"navlist\">\n");
      out.write("\t\t\t<li><a href=\"/FabFlix/Main\">Home</a></li>\n");
      out.write("\t\t\t<li><a href=\"/FabFlix/search\">Search</a></li>\n");
      out.write("\t\t\t<li><a href=\"/FabFlix/Browse?by=genre\">Browse By Genre</a></li>\n");
      out.write("\t\t\t<li><a href=\"/FabFlix/Browse?by=title\">Browse By Title</a></li>\n");
      out.write("\t\t\t<li><a href=\"/FabFlix/Cart\">Cart</a></li>\n");
      out.write("\t\t\t<li><a href=\"/FabFlix/Logout\">Logout</a></li>\n");
      out.write("\t\t</ul>\t\n");
      out.write("\t</nav>\n");
      out.write("</header>");
      out.write('\n');

	// This portion of the code is vital to make it so the user cannot access a page w/o being logged in.
    if ((session.getAttribute("email") == null) || (session.getAttribute("email") == "")) {
		String redirectURL = loginPath+"?message=";

        RequestDispatcher dispatcher = null;
		dispatcher = getServletContext().getRequestDispatcher(redirectURL);
        dispatcher.forward(request, response);
    }


      out.write('\n');
ArrayList<String> movieTitles = (ArrayList<String>)request.getAttribute("movieTitles"); 
      out.write('\n');
ArrayList<Integer> movieIDs = (ArrayList<Integer>)request.getAttribute("movieIDs"); 
      out.write("\n");
      out.write("\t<div>\n");
      out.write("\t\t<h2>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${star}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</h2>\n");
      out.write("\t\t<div class=\"starInfoDiv\"><img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${photo}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" alt=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${star}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(" Photo\"/></div>\n");
      out.write("\t\t<div>\n");
      out.write("\t\t\t<div class=\"starInfoDiv\"><div class=\"starInfoHeader\">Star ID#:</div> ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${star_id}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</div>\n");
      out.write("\t\t\t<div class=\"starInfoDiv\"><div class=\"starInfoHeader\">Star Name:</div> ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${star}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</div>\n");
      out.write("\t\t\t<div class=\"starInfoDiv\"><div class=\"starInfoHeader\">Date of Birth:</div> ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${dob}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</div>\n");
      out.write("\t\t\t<div class=\"starInfoHeader\">Movies:</div> <br/>\n");
      out.write("\t\t\t<div>\n");
      out.write("\t\t\t\t<div class=\"indent\">\n");
      out.write("\t\t\t\t\t");
for(int i = 0;  i < movieTitles.size(); i++) {
      out.write("\n");
      out.write("\t\t\t\t\t\t");
request.setAttribute("tempString", (String)movieTitles.get(i));
      out.write("\n");
      out.write("\t\t\t\t\t\t");
request.setAttribute("tempInt", (int)movieIDs.get(i));
      out.write("\n");
      out.write("\t\t\t\t\t\t<a href=\"/FabFlix/MoviePage?movieid=");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${tempInt}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write('"');
      out.write('>');
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${tempString}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</a>\n");
      out.write("\t\t\t\t\t\t</div><div class=\"indent\">\n");
      out.write("\t\t\t\t\t");
} 
      out.write("\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t</div>\n");
      out.write("\t</div>\n");
      out.write("</body>\n");
      out.write("</html>\n");
      out.write("\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
