/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.68
 * Generated at: 2016-04-21 12:26:55 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.sun.rowset.CachedRowSetImpl;
import java.sql.ResultSet;

public final class search_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/WEB-INF/var.jsp", Long.valueOf(1461240684551L));
    _jspx_dependants.put("/WEB-INF/header.jsp", Long.valueOf(1461241429375L));
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=ISO-8859-1\">\r\n");
      out.write("<title>Search Movies</title>\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"css/styles.css\">\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("<!-- This File holds the Login Details and other Globals -->\r\n");

	// This is the Login for the DB
	String DB_USER= "root"; 
	String DB_PASS="pops711";
	// This is the location of the Login Portal
	String loginPath="/Index";
	// This is the location of the Login-Authentication
	String authLoginPath="Login";	
	// This is the location of the Logout script
	String logoutPath="logout.jsp";	
	//This is the location of the HomePage
	String homePath="Main";
	// This is the location of the Search Page
	String searchPath="";	
	// This is the location of the General Browsing Page and the sub-pages
	String browsePath="browse.jsp";
	String browseGenre="Browse?by=genre";
	String browseTitle="Browse?by=title";
	// This is the location of the movie-list after you find one.
	String movieListPath="MovieList";

      out.write("\r\n");
      out.write("<header class=\"siteHeader\">\r\n");
      out.write("\t<nav class=\"navbar\">\r\n");
      out.write("\t\t<ul class=\"navlist\">\r\n");
      out.write("\t\t\t<li><a href=\"/FabFlix/Main\">Home</a></li>\r\n");
      out.write("\t\t\t<li><a href=\"/FabFlix/search\">Search</a></li>\r\n");
      out.write("\t\t\t<li><a href=\"/FabFlix/Browse\">Browse</a></li>\r\n");
      out.write("\t\t</ul>\t\r\n");
      out.write("\t</nav>\r\n");
      out.write("</header>");
      out.write('\r');
      out.write('\n');

	// This portion of the code is vital to make it so the user cannot access a page w/o being logged in.
    if ((session.getAttribute("email") == null) || (session.getAttribute("email") == "")) {
		String redirectURL = loginPath+"?message=";

        RequestDispatcher dispatcher = null;
		dispatcher = getServletContext().getRequestDispatcher(redirectURL);
        dispatcher.forward(request, response);
    }


      out.write("\r\n");
      out.write("\t<div class=\"searchContainer\">\r\n");
      out.write("\t\t\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<input \r\n");
      out.write("\t\t\tid=\"nameSearchBox\" \r\n");
      out.write("\t\t\tclass=\"dbSearchBox\" \r\n");
      out.write("\t\t\tplaceholder=\"Star Name\" \r\n");
      out.write("\t\t\tonkeydown = \"if (event.keyCode == 13)\r\n");
      out.write("                        document.getElementById('searchButton').click()\" \r\n");
      out.write("        \t/>\r\n");
      out.write("        <input \r\n");
      out.write("\t\t\tid=\"titleSearchBox\" \r\n");
      out.write("\t\t\tclass=\"dbSearchBox\" \r\n");
      out.write("\t\t\tplaceholder=\"Movie Title\" \r\n");
      out.write("\t\t\tonkeydown = \"if (event.keyCode == 13)\r\n");
      out.write("                        document.getElementById('searchButton').click()\" \r\n");
      out.write("        \t/>\r\n");
      out.write("        <input \r\n");
      out.write("\t\t\tid=\"directorSearchBox\" \r\n");
      out.write("\t\t\tclass=\"dbSearchBox\" \r\n");
      out.write("\t\t\tplaceholder=\"Director Full-Name\" \r\n");
      out.write("\t\t\tonkeydown = \"if (event.keyCode == 13)\r\n");
      out.write("                        document.getElementById('searchButton').click()\" \r\n");
      out.write("        \t/>\r\n");
      out.write("        <input \r\n");
      out.write("\t\t\tid=\"yearSearchBox\" \r\n");
      out.write("\t\t\tclass=\"dbSearchBox\" \r\n");
      out.write("\t\t\tplaceholder=\"Year of Release\" \r\n");
      out.write("\t\t\tonkeydown = \"if (event.keyCode == 13)\r\n");
      out.write("                        document.getElementById('searchButton').click()\" \r\n");
      out.write("        \t/>\r\n");
      out.write("\t\t<input \r\n");
      out.write("\t\t\tid=\"searchButton\" \r\n");
      out.write("\t\t\tclass=\"searchButton\" \r\n");
      out.write("\t\t\ttype=\"button\" \r\n");
      out.write("\t\t\tvalue=\"search\" \r\n");
      out.write("\t\t\tonclick=\"submitSearch()\" \r\n");
      out.write("\t\t\t/>\r\n");
      out.write("\t<script type=\"text/javascript\" src=\"js/search.js\"></script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>\t");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
