/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.33
 * Generated at: 2016-05-03 18:47:27 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.ArrayList;
import com.sun.rowset.CachedRowSetImpl;
import java.sql.ResultSet;
import fabflix.Global;
import fabflix.Global;

public final class movie_002dlist_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(1);
    _jspx_dependants.put("/WEB-INF/site-header.jsp", Long.valueOf(1462296887000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("com.sun.rowset.CachedRowSetImpl");
    _jspx_imports_classes.add("java.sql.ResultSet");
    _jspx_imports_classes.add("fabflix.Global");
    _jspx_imports_classes.add("java.util.ArrayList");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write(" \n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("\t<meta http-equiv=\"Content-Type\" content=\"text/html; charset=ISO-8859-1\">\n");
      out.write("\t<link rel=\"stylesheet\" type=\"text/css\" href=\"css/styles.css\">\n");
      out.write("\t<title>Search Movies</title>\n");
      out.write("</head>\n");
if(request.getParameter("addToCart") != null && !request.getParameter("addToCart").equals("")){ 
      out.write("\n");
      out.write("<body onload='updateQueryStringParameter(\"addToCart\", \"\")'>\n");
}else{ 
      out.write("\n");
      out.write("<body>\n");
} 
      out.write('\n');
      out.write("\n");
      out.write("<header class=\"siteHeader\">\n");
      out.write("\t<nav class=\"navbar\">\n");
      out.write("\t\t<ul class=\"navlist\">\n");
      out.write("\t\t\t<li><a href=\"");
      out.print(request.getContextPath());
      out.write("/Home\">Home</a></li>\n");
      out.write("\t\t\t<li><a href=\"");
      out.print(request.getContextPath());
      out.write("/Search\">Search</a></li>\n");
      out.write("\t\t\t<li><a href=\"");
      out.print(request.getContextPath());
      out.write("/Browse\">Browse</a></li>\n");
      out.write("\t\t\t<li><a href=\"");
      out.print(request.getContextPath());
      out.write("/Cart\">View Cart</a></li>\n");
      out.write("\t\t\t");
 if(!(session.getAttribute("email") == null) || (session.getAttribute("email") == "")){
      out.write("\n");
      out.write("\t\t\t\t<a href=");
      out.print(Global.logoutServletPath+"");
      out.write("><input class=\"absolute-right\" type=\"button\" value=\"logout\"/></a>\n");
      out.write("\t\t\t");
} 
      out.write("\n");
      out.write("\t\t</ul>\t\n");
      out.write("\t</nav>\n");
      out.write("</header>");
      out.write('\n');
CachedRowSetImpl rs = (CachedRowSetImpl)request.getAttribute("rs"); 
      out.write('\n');
ArrayList<ArrayList<String>> moviesAndStars = (ArrayList<ArrayList<String>>)request.getAttribute("moviesAndStars"); 
      out.write('\n');
ArrayList<ArrayList<String>> moviesAndGenres = (ArrayList<ArrayList<String>>)request.getAttribute("moviesAndGenres"); 
      out.write('\n');
ArrayList<ArrayList<Integer>> moviesAndGenreIDs = (ArrayList<ArrayList<Integer>>)request.getAttribute("moviesAndGenreIDs"); 
      out.write('\n');
Integer pageNum = (Integer)request.getAttribute("pageNum"); 
      out.write('\n');
if(rs != null) {
      out.write('\n');
int j = 0; 
      out.write('\n');
String tempString; 
      out.write('\n');
Integer tempInt; 
      out.write("\n");
      out.write("\t<div class=\"searchContainer\">\n");
      out.write("\t\t<input \n");
      out.write("\t\t\tid=\"dbSearchBox\" \n");
      out.write("\t\t\tclass=\"dbSearchBox\" \n");
      out.write("\t\t\tplaceholder=\"Movie Title, star name, year, or director \" \n");
      out.write("\t\t\tonkeydown = \"if (event.keyCode == 13)\n");
      out.write("                        document.getElementById('searchButton').click()\" \n");
      out.write("        \t/>\n");
      out.write("\t\t<input \n");
      out.write("\t\t\tid=\"searchButton\" \n");
      out.write("\t\t\tclass=\"searchButton\" \n");
      out.write("\t\t\ttype=\"button\" \n");
      out.write("\t\t\tvalue=\"search\" \n");
      out.write("\t\t\tonclick=\"submitSearch()\" \n");
      out.write("\t\t\t/>\n");
      out.write("\t</div>\n");
      out.write("\t\n");
      out.write("\t\t<div class=\"movieListHeader\">\n");
      out.write("\t\t\t<div>Movie ID</div> \n");
      out.write("\t\t\t<div class=\"movieName\" onclick='updateQueryStringParameter(\"orderby\", \"title\")'>Movie Title</div> \n");
      out.write("\t\t\t<div class=\"movieYear\" onclick='updateQueryStringParameter(\"orderby\", \"year\")'>Year of Release</div>  \n");
      out.write("\t\t\t<div>Director</div>\n");
      out.write("\t\t\t<div class=\"movieStarList\">Star Names</div>\n");
      out.write("\t\t\t<div class=\"movieGenreList\">Genres</div>\n");
      out.write("\t\t</div>\n");
      out.write("\t\t");
while(rs.next()){
      out.write("\n");
      out.write("\t\t\t<div class=\"movieRow\">\n");
      out.write("\t\t\t\t<div class=\"movieInfoDiv\"> \n");
      out.write("\t\t\t\t\t");
      out.print(rs.getInt(1));
      out.write("\n");
      out.write("\t\t\t\t\t<input \n");
      out.write("\t\t\t\t\t\tid=\"addToCart\" \n");
      out.write("\t\t\t\t\t\tclass=\"addToCart\" \n");
      out.write("\t\t\t\t\t\ttype=\"button\" \n");
      out.write("\t\t\t\t\t\tvalue=\"Add To Cart\" \n");
      out.write("\t\t\t\t\t\tonclick='updateQueryStringParameter(\"addToCart\",");
      out.print(rs.getInt(1));
      out.write(" )' />\n");
      out.write("\t\t\t\t</div> \n");
      out.write("\t\t\t\t<div class=\"movieInfoDiv movieName\"> <a href=\"/fabflix/MoviePage?movieid=");
      out.print(rs.getInt(1));
      out.write('"');
      out.write('>');
      out.print(rs.getString(2));
      out.write("</a> </div> \n");
      out.write("\t\t\t\t<div class=\"movieInfoDiv\"> ");
      out.print(rs.getString(3));
      out.write(" </div>  \n");
      out.write("\t\t\t\t<div class=\"movieInfoDiv\"> ");
      out.print(rs.getString(4));
      out.write(" </div>\n");
      out.write("\t\t\t\t<div class=\"movieStarList movieInfoDiv\">\n");
      out.write("\t\t\t\t\t<div>\n");
      out.write("\t\t\t\t\t");
for(int i = 0;  i < moviesAndStars.get(j).size(); i++) {
      out.write("\n");
      out.write("\t\t\t\t\t\t");
tempString = (String)moviesAndStars.get(j).get(i);
      out.write("\n");
      out.write("\t\t\t\t\t\t<a href=\"/fabflix/StarPage?starname=");
      out.print(tempString);
      out.write('"');
      out.write('>');
      out.print(tempString);
      out.write("</a>\n");
      out.write("\t\t\t\t\t\t");
if((i+1)%3 == 0){ 
      out.write("\n");
      out.write("\t\t\t\t\t\t</div><div>\n");
      out.write("\t\t\t\t\t\t");
} 
      out.write("\n");
      out.write("\t\t\t\t\t");
} 
      out.write("\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t\t<div class=\"movieGenreList movieInfoDiv\">\n");
      out.write("\t\t\t\t\t<div>\n");
      out.write("\t\t\t\t\t");
for(int i = 0;  i < moviesAndGenres.get(j).size(); i++) {
      out.write("\n");
      out.write("\t\t\t\t\t\t");
tempString = (String)moviesAndGenres.get(j).get(i);
      out.write("\n");
      out.write("\t\t\t\t\t\t");
tempInt = (Integer)moviesAndGenreIDs.get(j).get(i);
      out.write("\n");
      out.write("\t\t\t\t\t\t<a href=\"MovieList?type=genre&id=");
      out.print(tempInt);
      out.write('"');
      out.write('>');
      out.print(tempString);
      out.write("</a>\n");
      out.write("\t\t\t\t\t\t");
if((i+1)%4 == 0){ 
      out.write("\n");
      out.write("\t\t\t\t\t\t</div><div>\n");
      out.write("\t\t\t\t\t\t");
} 
      out.write("\n");
      out.write("\t\t\t\t\t");
} 
      out.write("\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t\t");
j++; 
      out.write('\n');
      out.write('	');
      out.write('	');
} 
      out.write('\n');
      out.write('	');
      out.write('	');
if(pageNum != null) {
      out.write("\n");
      out.write("\t\t\t");
if(!pageNum.equals("")) {
      out.write("\n");
      out.write("\t\t\t\t");
if(pageNum > 1) {
      out.write("\n");
      out.write("\t\t\t\t\t<input \n");
      out.write("\t\t\t\t\t\tid=\"prevButton\" \n");
      out.write("\t\t\t\t\t\tclass=\"prevButton\" \n");
      out.write("\t\t\t\t\t\ttype=\"button\" \n");
      out.write("\t\t\t\t\t\tvalue=\"prev\" \n");
      out.write("\t\t\t\t\t\tonclick='decrementQueryStringParameter(\"pagenum\", ");
      out.print(pageNum);
      out.write(")' \n");
      out.write("\t\t\t\t\t\t/>\n");
      out.write("\t\t\t\t");
}
      out.write("\n");
      out.write("\t\t\t");
} 
      out.write('\n');
      out.write('	');
      out.write('	');
} else {
      out.write("\n");
      out.write("\t\t\t<input \n");
      out.write("\t\t\t\tid=\"prevButton\" \n");
      out.write("\t\t\t\tclass=\"prevButton\" \n");
      out.write("\t\t\t\ttype=\"button\" \n");
      out.write("\t\t\t\tvalue=\"prev\" \n");
      out.write("\t\t\t\tonclick='decrementQueryStringParameter(\"pagenum\", 2)' \n");
      out.write("\t\t\t\t/>\n");
      out.write("\t\t");
} 
      out.write('\n');
      out.write('	');
      out.write('	');
if( !(j < 10) ){ 
      out.write("\n");
      out.write("\t\t\t");
if(pageNum != null) {
      out.write("\n");
      out.write("\t\t\t\t");
if(!pageNum.equals("")) {
      out.write("\n");
      out.write("\t\t\t\t\t<input \n");
      out.write("\t\t\t\t\t\tid=\"nextButton\" \n");
      out.write("\t\t\t\t\t\tclass=\"nextButton\" \n");
      out.write("\t\t\t\t\t\ttype=\"button\" \n");
      out.write("\t\t\t\t\t\tvalue=\"next\" \n");
      out.write("\t\t\t\t\t\tonclick='incrementQueryStringParameter(\"pagenum\", ");
      out.print(pageNum);
      out.write(")' \n");
      out.write("\t\t\t\t\t\t/>\n");
      out.write("\t\t\t\t");
} 
      out.write("\n");
      out.write("\t\t\t");
} else {
      out.write("\n");
      out.write("\t\t\t\t<input \n");
      out.write("\t\t\t\t\tid=\"nextButton\" \n");
      out.write("\t\t\t\t\tclass=\"nextButton\" \n");
      out.write("\t\t\t\t\ttype=\"button\" \n");
      out.write("\t\t\t\t\tvalue=\"next\" \n");
      out.write("\t\t\t\t\tonclick='incrementQueryStringParameter(\"pagenum\", 1)' \n");
      out.write("\t\t\t\t\t/>\n");
      out.write("\t\t\t");
} 
      out.write('\n');
      out.write('	');
      out.write('	');
} 
      out.write('\n');
      out.write('	');
}else{ 
      out.write("\n");
      out.write("\t<p>No movies match your search</p>\n");
      out.write("\t");
} 
      out.write("\n");
      out.write("\t<script type=\"text/javascript\" src=\"js/movie-list.js\"></script>\n");
      out.write("</body>\n");
      out.write("</html>\t");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
