/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.68
 * Generated at: 2016-05-01 04:24:46 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.ArrayList;
import com.sun.rowset.CachedRowSetImpl;
import java.sql.ResultSet;
import fabflix.Global;

public final class movie_002dlist_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(1);
    _jspx_dependants.put("/WEB-INF/site-header.jsp", Long.valueOf(1461988399018L));
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write(" \r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("\t<meta http-equiv=\"Content-Type\" content=\"text/html; charset=ISO-8859-1\">\r\n");
      out.write("\t<link rel=\"stylesheet\" type=\"text/css\" href=\"css/styles.css\">\r\n");
      out.write("\t<title>Search Movies</title>\r\n");
      out.write("</head>\r\n");
if(request.getParameter("addToCart") != null && !request.getParameter("addToCart").equals("")){ 
      out.write("\r\n");
      out.write("<body onload='updateQueryStringParameter(\"addToCart\", \"\")'>\r\n");
}else{ 
      out.write("\r\n");
      out.write("<body>\r\n");
} 
      out.write('\r');
      out.write('\n');
      out.write("<header class=\"siteHeader\">\r\n");
      out.write("\t<nav class=\"navbar\">\r\n");
      out.write("\t\t<ul class=\"navlist\">\r\n");
      out.write("\t\t\t<li><a href=\"");
      out.print(request.getContextPath());
      out.write("/Home\">Home</a></li>\r\n");
      out.write("\t\t\t<li><a href=\"");
      out.print(request.getContextPath());
      out.write("/Search\">Search</a></li>\r\n");
      out.write("\t\t\t<li><a href=\"");
      out.print(request.getContextPath());
      out.write("/Browse\">Browse</a></li>\r\n");
      out.write("\t\t\t<li><a href=\"");
      out.print(request.getContextPath());
      out.write("/Cart\">View Cart</a></li>\r\n");
      out.write("\t\t</ul>\t\r\n");
      out.write("\t</nav>\r\n");
      out.write("</header>");
      out.write('\r');
      out.write('\n');
CachedRowSetImpl rs = (CachedRowSetImpl)request.getAttribute("rs"); 
      out.write('\r');
      out.write('\n');
ArrayList<ArrayList<String>> moviesAndStars = (ArrayList<ArrayList<String>>)request.getAttribute("moviesAndStars"); 
      out.write('\r');
      out.write('\n');
ArrayList<ArrayList<String>> moviesAndGenres = (ArrayList<ArrayList<String>>)request.getAttribute("moviesAndGenres"); 
      out.write('\r');
      out.write('\n');
ArrayList<ArrayList<Integer>> moviesAndGenreIDs = (ArrayList<ArrayList<Integer>>)request.getAttribute("moviesAndGenreIDs"); 
      out.write('\r');
      out.write('\n');
Integer pageNum = (Integer)request.getAttribute("pageNum"); 
      out.write('\r');
      out.write('\n');
if(rs != null) {
      out.write('\r');
      out.write('\n');
int j = 0; 
      out.write('\r');
      out.write('\n');
String tempString; 
      out.write('\r');
      out.write('\n');
Integer tempInt; 
      out.write("\r\n");
      out.write("\t<div class=\"searchContainer\">\r\n");
      out.write("\t\t<input \r\n");
      out.write("\t\t\tid=\"dbSearchBox\" \r\n");
      out.write("\t\t\tclass=\"dbSearchBox\" \r\n");
      out.write("\t\t\tplaceholder=\"Movie Title, star name, year, or director \" \r\n");
      out.write("\t\t\tonkeydown = \"if (event.keyCode == 13)\r\n");
      out.write("                        document.getElementById('searchButton').click()\" \r\n");
      out.write("        \t/>\r\n");
      out.write("\t\t<input \r\n");
      out.write("\t\t\tid=\"searchButton\" \r\n");
      out.write("\t\t\tclass=\"searchButton\" \r\n");
      out.write("\t\t\ttype=\"button\" \r\n");
      out.write("\t\t\tvalue=\"search\" \r\n");
      out.write("\t\t\tonclick=\"submitSearch()\" \r\n");
      out.write("\t\t\t/>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t\r\n");
      out.write("\t\t<div class=\"movieListHeader\">\r\n");
      out.write("\t\t\t<div>Movie ID</div> \r\n");
      out.write("\t\t\t<div class=\"movieName\" onclick='updateQueryStringParameter(\"orderby\", \"title\")'>Movie Title</div> \r\n");
      out.write("\t\t\t<div class=\"movieYear\" onclick='updateQueryStringParameter(\"orderby\", \"year\")'>Year of Release</div>  \r\n");
      out.write("\t\t\t<div>Director</div>\r\n");
      out.write("\t\t\t<div class=\"movieStarList\">Star Names</div>\r\n");
      out.write("\t\t\t<div class=\"movieGenreList\">Genres</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t");
while(rs.next()){
      out.write("\r\n");
      out.write("\t\t\t<div class=\"movieRow\">\r\n");
      out.write("\t\t\t\t<div class=\"movieInfoDiv\"> \r\n");
      out.write("\t\t\t\t\t");
      out.print(rs.getInt(1));
      out.write("\r\n");
      out.write("\t\t\t\t\t<input \r\n");
      out.write("\t\t\t\t\t\tid=\"addToCart\" \r\n");
      out.write("\t\t\t\t\t\tclass=\"addToCart\" \r\n");
      out.write("\t\t\t\t\t\ttype=\"button\" \r\n");
      out.write("\t\t\t\t\t\tvalue=\"Add To Cart\" \r\n");
      out.write("\t\t\t\t\t\tonclick='updateQueryStringParameter(\"addToCart\",");
      out.print(rs.getInt(1));
      out.write(" )' />\r\n");
      out.write("\t\t\t\t</div> \r\n");
      out.write("\t\t\t\t<div class=\"movieInfoDiv movieName\"> <a href=\"/fabflix/MoviePage?movieid=");
      out.print(rs.getInt(1));
      out.write('"');
      out.write('>');
      out.print(rs.getString(2));
      out.write("</a> </div> \r\n");
      out.write("\t\t\t\t<div class=\"movieInfoDiv\"> ");
      out.print(rs.getString(3));
      out.write(" </div>  \r\n");
      out.write("\t\t\t\t<div class=\"movieInfoDiv\"> ");
      out.print(rs.getString(4));
      out.write(" </div>\r\n");
      out.write("\t\t\t\t<div class=\"movieStarList movieInfoDiv\">\r\n");
      out.write("\t\t\t\t\t<div>\r\n");
      out.write("\t\t\t\t\t");
for(int i = 0;  i < moviesAndStars.get(j).size(); i++) {
      out.write("\r\n");
      out.write("\t\t\t\t\t\t");
tempString = (String)moviesAndStars.get(j).get(i);
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<a href=\"/fabflix/StarPage?starname=");
      out.print(tempString);
      out.write('"');
      out.write('>');
      out.print(tempString);
      out.write("</a>\r\n");
      out.write("\t\t\t\t\t\t");
if((i+1)%3 == 0){ 
      out.write("\r\n");
      out.write("\t\t\t\t\t\t</div><div>\r\n");
      out.write("\t\t\t\t\t\t");
} 
      out.write("\r\n");
      out.write("\t\t\t\t\t");
} 
      out.write("\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"movieGenreList movieInfoDiv\">\r\n");
      out.write("\t\t\t\t\t<div>\r\n");
      out.write("\t\t\t\t\t");
for(int i = 0;  i < moviesAndGenres.get(j).size(); i++) {
      out.write("\r\n");
      out.write("\t\t\t\t\t\t");
tempString = (String)moviesAndGenres.get(j).get(i);
      out.write("\r\n");
      out.write("\t\t\t\t\t\t");
tempInt = (Integer)moviesAndGenreIDs.get(j).get(i);
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<a href=\"MovieList?type=genre&id=");
      out.print(tempInt);
      out.write('"');
      out.write('>');
      out.print(tempString);
      out.write("</a>\r\n");
      out.write("\t\t\t\t\t\t");
if((i+1)%4 == 0){ 
      out.write("\r\n");
      out.write("\t\t\t\t\t\t</div><div>\r\n");
      out.write("\t\t\t\t\t\t");
} 
      out.write("\r\n");
      out.write("\t\t\t\t\t");
} 
      out.write("\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t");
j++; 
      out.write("\r\n");
      out.write("\t\t");
} 
      out.write("\r\n");
      out.write("\t\t");
if(pageNum != null) {
      out.write("\r\n");
      out.write("\t\t\t");
if(!pageNum.equals("")) {
      out.write("\r\n");
      out.write("\t\t\t\t");
if(pageNum > 1) {
      out.write("\r\n");
      out.write("\t\t\t\t\t<input \r\n");
      out.write("\t\t\t\t\t\tid=\"prevButton\" \r\n");
      out.write("\t\t\t\t\t\tclass=\"prevButton\" \r\n");
      out.write("\t\t\t\t\t\ttype=\"button\" \r\n");
      out.write("\t\t\t\t\t\tvalue=\"prev\" \r\n");
      out.write("\t\t\t\t\t\tonclick='decrementQueryStringParameter(\"pagenum\", ");
      out.print(pageNum);
      out.write(")' \r\n");
      out.write("\t\t\t\t\t\t/>\r\n");
      out.write("\t\t\t\t");
}
      out.write("\r\n");
      out.write("\t\t\t");
} 
      out.write("\r\n");
      out.write("\t\t");
} else {
      out.write("\r\n");
      out.write("\t\t\t<input \r\n");
      out.write("\t\t\t\tid=\"prevButton\" \r\n");
      out.write("\t\t\t\tclass=\"prevButton\" \r\n");
      out.write("\t\t\t\ttype=\"button\" \r\n");
      out.write("\t\t\t\tvalue=\"prev\" \r\n");
      out.write("\t\t\t\tonclick='decrementQueryStringParameter(\"pagenum\", 2)' \r\n");
      out.write("\t\t\t\t/>\r\n");
      out.write("\t\t");
} 
      out.write("\r\n");
      out.write("\t\t");
if( !(j < 10) ){ 
      out.write("\r\n");
      out.write("\t\t\t");
if(pageNum != null) {
      out.write("\r\n");
      out.write("\t\t\t\t");
if(!pageNum.equals("")) {
      out.write("\r\n");
      out.write("\t\t\t\t\t<input \r\n");
      out.write("\t\t\t\t\t\tid=\"nextButton\" \r\n");
      out.write("\t\t\t\t\t\tclass=\"nextButton\" \r\n");
      out.write("\t\t\t\t\t\ttype=\"button\" \r\n");
      out.write("\t\t\t\t\t\tvalue=\"next\" \r\n");
      out.write("\t\t\t\t\t\tonclick='incrementQueryStringParameter(\"pagenum\", ");
      out.print(pageNum);
      out.write(")' \r\n");
      out.write("\t\t\t\t\t\t/>\r\n");
      out.write("\t\t\t\t");
} 
      out.write("\r\n");
      out.write("\t\t\t");
} else {
      out.write("\r\n");
      out.write("\t\t\t\t<input \r\n");
      out.write("\t\t\t\t\tid=\"nextButton\" \r\n");
      out.write("\t\t\t\t\tclass=\"nextButton\" \r\n");
      out.write("\t\t\t\t\ttype=\"button\" \r\n");
      out.write("\t\t\t\t\tvalue=\"next\" \r\n");
      out.write("\t\t\t\t\tonclick='incrementQueryStringParameter(\"pagenum\", 1)' \r\n");
      out.write("\t\t\t\t\t/>\r\n");
      out.write("\t\t\t");
} 
      out.write("\r\n");
      out.write("\t\t");
} 
      out.write('\r');
      out.write('\n');
      out.write('	');
}else{ 
      out.write("\r\n");
      out.write("\t<p>No movies match your search</p>\r\n");
      out.write("\t");
} 
      out.write("\r\n");
      out.write("\t<script type=\"text/javascript\" src=\"js/movie-list.js\"></script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>\t");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
